### ISSUE TITLE
HTTP / 1.1 403 Forbidden (HTTP ERROR 403)

### ISSUE THREAD

**Issue by omansak** [flagbug/YoutubeExtractor#238]
Many URLs has this error.
Ex : https://www.youtube.com/watch?v=HaoNiqITEJo

**Comment by mysteryx93** [comment]
This video works for me.

But I do get Forbidden (403) on another video as noted here
https://github.com/flagbug/YoutubeExtractor/issues/236

**Comment by mysteryx93** [comment]
Oh, you get the error because of the change that was fixed recently. You need to download the source code and compile yourself until a new version is released.

**Comment by omansak** [comment]
Need uptade on nuget

**Comment by markwalsh-liverpool** [comment]
Downloading the source and compiling is NOT a resolution.  It's a hack.  The latest (buildable) version of the master branch should always be in Nuget, please see my issue which would resolve this. #237

**Comment by jphellemons** [comment]
I still have a 403 forbidden on line 45 of VideoDownloader.cs at the GetResponse. And I have the latest source code...

**Comment by Taki7o7** [comment]
i still have the same issue :/

Nuget YTEx version 0.10.11
